server:
  port: 8080
  servlet:
    context-path: /my-journal-app

spring:

  profiles:
    active: secrets  # load application-secrets.yml

  redis:
    host: localhost
    port: 6379

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: email@gmail.com
    password: something
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: ${CONFLUENT_KAFKA_BOOTSTRAP_SERVER_URI}

    properties:
      security.protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas.config: >
          org.apache.kafka.common.security.plain.PlainLoginModule required 
          username=${USERNAME} 
          password=${PASSWORD};

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: mail-sender
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.svats.journalApp.model

client.id: ${CONFLUENT_CLIENT_ID}

springdoc.swagger-ui.path: /docs